version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: school_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_registry
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./school-registry
    container_name: school_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school_registry?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  frontend:
    build:
      context: ./school-registry-frontend
    container_name: school_frontend
    restart: always
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data:
